# name: Hello World
# on:
#   push:
#     branches:
#       - main

# jobs:
#   hello:
#     runs-on: ubuntu-24.04-arm

#     steps:
#       - name: Print Hello World
#         run: 'echo "Heyy,there Rajkumar"'

name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Heyy, there Rajkumar 👋"

      - name: Show current date and time
        run: date

      - name: List files in the repository
        run: ls -la
